package com.roguesmp.event;

import com.roguesmp.item.SmpItem;
import com.roguesmp.player.SmpPlayer;
import org.bukkit.event.Event;
import org.bukkit.event.HandlerList;
import org.jetbrains.annotations.NotNull;

/**
 * Fired before an item's {@code DurabilityComponent} current durability is actually changed (loss
 * or repair), mirroring how {@code DamageEvent} is fired pre-commit in this codebase.
 * {@link #getChangeAmount()} starts out as the proposed delta (negative for loss) but is mutable
 * via {@link #setChangeAmount(int)} - a {@link com.roguesmp.item.ability.ItemAbility} (see
 * {@code onDurabilityChange}) can adjust it to reduce/increase the actual wear, or veto the change
 * outright by setting it to {@code 0}. {@code DurabilityLossMechanic} reads back whatever
 * {@link #getChangeAmount()} ends up being and applies it against the item's current durability -
 * old/max durability aren't duplicated here since {@link #getItem()}'s own
 * {@code DurabilityComponent} still reflects the pre-commit values.
 * <p>
 * {@code SmpItem#generateItemStack} is comparatively expensive to run on every single point of
 * durability loss, so the stack isn't regenerated by default (the durability value is still
 * persisted cheaply either way) - an ability whose display/stats depend on durability (see
 * {@code UnyieldingEdge}) sets {@link #setShouldUpdateItem(boolean)} to request a full refresh
 * when the change is actually worth reacting to (e.g. crossed a threshold).
 */
public class DurabilityChangedEvent extends Event {
    private static final HandlerList HANDLERS = new HandlerList();

    private final SmpItem item;
    private final SmpPlayer player;
    private int changeAmount;
    private boolean shouldUpdateItem = false;

    public DurabilityChangedEvent(SmpItem item, SmpPlayer player, int changeAmount) {
        this.item = item;
        this.player = player;
        this.changeAmount = changeAmount;
    }

    public SmpItem getItem() {
        return item;
    }

    public SmpPlayer getPlayer() {
        return player;
    }

    public int getChangeAmount() {
        return changeAmount;
    }

    public void setChangeAmount(int changeAmount) {
        this.changeAmount = changeAmount;
    }

    public boolean shouldUpdateItem() {
        return shouldUpdateItem;
    }

    public void setShouldUpdateItem(boolean shouldUpdateItem) {
        this.shouldUpdateItem = shouldUpdateItem;
    }

    @Override
    public @NotNull HandlerList getHandlers() {
        return HANDLERS;
    }

    public static HandlerList getHandlerList() {
        return HANDLERS;
    }
}
