name: RogueSmpCore
version: '1.0-SNAPSHOT'
main: com.roguesmp.RogueSmpCore
api-version: '26.2'
description: Rework plugin
depend:
  - CommandAPI
  - FastAsyncWorldEdit
  - TAB
  - PlaceholderAPI
  - Multiverse-Core
  - WorldGuard
  - polarpaper
  - LuckPerms
